# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Print version  
      run:  sed -i "s/1.0.0/1.0.$GITHUB_RUN_NUMBER.0/g" Tddy.Core/Tddy.Core.csproj  && cat Tddy.Core/Tddy.Core.csproj
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Push
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release Tddy.Core/Tddy.Core.csproj -o . && dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
    - name: Tag
      run: git tag 1.0.$GITHUB_RUN_NUMBER.0 && git push origin 1.0.$GITHUB_RUN_NUMBER.0
